### PR TITLE
Printing the json file using jsonlite

### PR DESCRIPTION
**Pull request by fong22e**
The code to print the json file is now in `OutputJSON.R`. There are 2 public functions in that file, `ddg.json` and `ddg.json.write`. `ddg.json`. `ddg.json` is the function which generates the json string and `ddg.json.write` is the function which takes the output from `ddg.json` and writes it to a file. The algorithm to print the json strings also use `jsonlite`, but a lot of post-processing was required to create the desired prov-json compliant format. `tests.xml` has also been updated accordingly to detect patterns in the new format.

The next steps are:
* comment the code using roxygen syntax
* add prov-json compliance testing to regression tests
* finish updating the json parser for DDGExplorer

### CODE REVIEW

**Comment by fong22e** [comment]
According to the Travis log, `FunctionOriginTest` failed as the test on Travis threw the following warning which created an extra node in the ddg:
```
package 'stringr' was built under R version 3.4.3 
```

I ran the tests on my local computer and they all passed. I am not sure what could be the problem...

**Comment by MKLau** [comment]
@fong22e 

One thought, your local run might have a different R version that matches the stringr version.

**Comment by blernermhc** [comment]
So, I can now see where Travis reports what version it is running and it is 3.4.2.  So, that would explain the error since it is getting a more recent version of stringr (for 3.4.3), but I don't know what to do about that yet.

**Comment by blernermhc** [comment]
Does it help to list stringr in the travis.yml file?

**Comment by blernermhc** [comment]
I think it's curious that the push Travis test passes but the pull request Travis test fails.  The configurations seems to be the same for both, but looking at the log.  We see for the test that passes:

image

and for the one that fails:

image

Any ideas why these should be different?  Or why Travis is run twice?  What do we expect to be done differently in each?

**Comment by blernermhc** [comment]
I still don't understand why the two tests are seeing different versions of stringr, but I believe that I understand the difference between the 2 Travis executions, and maybe there is a clue in that.

The pr test is testing the merge of the pull request.

The push test is testing the branch before the merge.

So, is something happening in the merge that causes the problem???

**Comment by fong22e** [comment]
Hmm... Has the development branch changed in the past week or so? I am currently on my way home so I am unable to try and merge development into the branch until about 8pm.

**Comment by blernermhc** [comment]
The last commit was Jan. 17.

**Comment by fong22e** [comment]
Thank you, Barbara! 

Since the last commit was Jan 17th, that means the development branch has already been merged into this branch. Therefore, there should be no additional changes when merging with this branch into development, since it has already been done in the reverse direction. This is, of course, assuming that I am understanding git merge correctly. My understand (or assumption) is that the code resulting from merging branch A into branch B is the same as the code resulting from merging branch B into branch A (assuming everything else is constant). Therefore, there should not be any differences between the code in the branch and the code after the pull request.

In my understanding, the code here is also limited to those that are tracked by git. I also understand that git will not let you switch branches if there are any uncommitted changes in any of its tracked files. I remember being able to switch branches after merging development and the only uncommitted changes are those in tests.xml that I am still working on. Both sets of code should still be using the old tests.xml file. Even if that was not the case, I have not done anything related to the stringr package so that should not affect anything in the sets of code.

**Comment by fong22e** [comment]
It looks like adding `stringr` to `.travis.yml` solved the issue. I guess this suggests that, for some reason, each test was running a different version of `stringr`. I don't know why that would be the case, though.

**Comment by blernermhc** [comment]
Whew!

**Comment by MKLau** [comment]
Yeah, nice job working through that!

If we're not explicitly calling for different stringr versions, I wonder if Travis is running the different tests on different nodes that have different R versions.

**Comment by fong22e** [comment]
Thank you!

That is such a weird thing for Travis to do though, if it is indeed doing that...

**Pull request merged**
