### PR TITLE
Implement Margo's fix + ddg.display.dgg() -> ddg.display()

### PR DESCRIPTION
**Pull request by tfjmp**
- ddg.display.ddg() is now simply ddg.display();
- starting DDG-Explorer does not block the use of RStudio anymore (user can go back and forth);

### CODE REVIEW

**Comment by MKLau** [comment]
Sorry, just saw this. Seems like it needs to get into Master. 

@erboose @blernermhc is this good to go?

@tfjmp what's the correct tagging for this?

**Comment by tfjmp** [comment]
@MKLau merging fix to master should lead to release 2.24.1

**Comment by blernermhc** [comment]
This should be merged into development, too, right?

**Comment by tfjmp** [comment]
You should do git pull origin fix in development, fix merge issue if any and push.

**Comment by blernermhc** [comment]
And master?

**Comment by blernermhc** [comment]
Ok, it is merged into development.  It is not merged into master.  Should it be?

**Pull request merged**
