### PR TITLE
removes PDSO file causing NPD error in CRAN check

### PR DESCRIPTION
**Pull request by MKLau**

### CODE REVIEW

**Comment by MKLau** [comment]
@tfjmp 

Hey Thomas, the Travis output says that the check stalled. Can you help interpret Travis? The last file that was running was something called "depends.R".

**Comment by tfjmp** [comment]
See how travis works with R: https://docs.travis-ci.com/user/languages/r/

We fail during: `R CMD check RDataTracker_2.25.1.tar.gz --as-cran`

Our `travis.yml` is there https://github.com/End-to-end-provenance/RDataTracker/blob/master/.travis.yml , so we fail during the default package test as "contributed by the community" (running the CRAN test) and do not reach the post success phase which runs `lintr`.

So the problem is `tests/depends.r`, it takes extremely long to run the first time so Travis gives up after 10 minutes (I did the test on my latop, it is indeed long). I believe making sure the dependencies in there are specified as discussed there: https://docs.travis-ci.com/user/languages/r/#Dependencies should solve the issue (adding `r_packages` in `travis.yaml` and the list of what is needed).

Example:
```
r_packages:
  - chron
```

Alternatively, depends.r could print stuff now and then so that travis does not timeout.

In fairness a human user may also think there is a problem if a script runs for 10 minutes without generating any output.

On a side note this script give a bunch of error of the kind: `installation of package ‘sysfonts’ had non-zero exit status`

**Comment by MKLau** [comment]
Ok good. I'll take a look this weekend.

**Comment by tfjmp** [comment]
Looking at the build history (https://travis-ci.org/End-to-end-provenance/RDataTracker/builds) it stopped to "work" (i.e. timeout) from this merge: https://github.com/End-to-end-provenance/RDataTracker/commit/c558331c36e8d4a2f0244e66c8fde70e4ba40e65

The last known good build was: https://github.com/End-to-end-provenance/RDataTracker/commit/36b821279a42a2b4c43e22973d9855b519c899cb

**Comment by tfjmp** [comment]
I simplified depends.r for the time being see https://github.com/tfjmp/RDataTracker/commit/9f10ae81d058204298cc24c2b257b4c4ee2e2228

However, Travis does not seem to particularly like the following:
```
## Directories
testDir <- "[DIR_LOCAL]/"
setwd(testDir)
```

The error is the following:
```
Error in setwd(testDir) : cannot change working directory
```

**Comment by MKLau** [comment]
This sounds like the path is not correctly specified. I don't know about [DIR_LOCAL]. Looks like it should be some general reference to a local file path, but I've never seen it used before.

**Comment by tfjmp** [comment]
That's blocking the check as far as I can tell.

**Comment by MKLau** [comment]
Could you start an issue about this in the main RDT issues? That way we can ask Barb and Emery about it.

**Comment by tfjmp** [comment]
Here it is: https://github.com/End-to-end-provenance/RDataTracker/issues/276

**Pull request merged**
