### PR TITLE
Add subdirectories for ddg files

### PR DESCRIPTION
**Pull request by erboose**
1. Add subdirectories (data, debug, scripts) under ddg directory.
2. Add details on sourced scripts to ddg.txt and ddg.json.
3. May require changes to DDG Explorer to view snapshot files.

### CODE REVIEW

**Comment by tfjmp** [comment]
Please check that overwriting previous change is done on purpose.

**Comment by erboose** [comment]
Most of these are expected changes to regression test outputs resulting from the restructuring of ddg files.

The addition of sourced script names and numbers to the JSON file may need to be reconciled with Thomas's recent updates to JSON output.

**Comment by tfjmp** [comment]
There is changes that are overwritten in RDataTracker.R

Please check this: https://github.com/End-to-end-provenance/RDataTracker/pull/143/files and go to RDataTracker.R.

**Comment by erboose** [comment]
OK.  I'll do the merge manually on scripts and then issue a new pull request.

**Comment by MKLau** [comment]
Ok, I hope you're not going to have to re-do too much work though! Let me know if I can help.

**Pull request closed without merging**
