### PR TITLE
Capture Standard Output

### PR DESCRIPTION
**Pull request by alexsiqingliu**
Captures all standard output from the execution of the R script using sink() function. Writes it to output.txt within ddg folder.

### CODE REVIEW

**Comment by blernermhc** [comment]
Hi Alex,

  Please add comments so that we know what the sink calls are for.  Also, it would be better to use a filename that is less likely to conflict with a name the R programmer might use.

Barbara

**Comment by MKLau** [comment]
@alexsiqingliu @blernermhc 

Hi Alex, have you added the comments that Barbara suggested and is this branch ready to merge?

**Comment by alexsiqingliu** [comment]
Hi Matt and Barbara, sorry for not doing this earlier, I seemed to have overlooked this update. Just added in the comments and changed the output file name to "standardOutputFromConsole.txt". Should I initiate a new pull request?

**Comment by tfjmp** [comment]
No do not. Any commit added to a branch with an open pull request are taken into account. If the pull request go through it will include your new commit.

**Comment by alexsiqingliu** [comment]
Got it, I'll leave it at that then.

**Comment by tfjmp** [comment]
Any reason to hold this merge?

**Comment by alexsiqingliu** [comment]
It didn't fit the specifications Barbara wanted. I just sank all standard output to a text file, but Barbara wanted to attach standard output from specific nodes.





On Mon, Oct 17, 2016 at 9:01 AM -0400, "Thomas Pasquier" <notifications@github.com> wrote:












Any reason to hold this merge?

**Comment by tfjmp** [comment]
All right thanks :-). I am closing the pull request then.

**Pull request closed without merging**
