### PR TITLE
Fixed non-local assignment to a certain degree

### PR DESCRIPTION
**Pull request by fong22e**
Related issue: [#189](https://github.com/End-to-end-provenance/RDataTracker/issues/189)

For non-local assignment cases using the `<<-` operator, it is working for cases where the non-local assignment statement is the last statement of a function.

However, it does not work in nested function cases, where the non-local assignment statement is not the last statement of a function.

@erboose , my test file is in the `examples-no-instrumentation/AssignmentOperatorsTest` directory. It contains only the R test file, `AssignmentOperatorsTest.R`.

Thank you all so very much!
Elizabeth

### CODE REVIEW

**Comment by blernermhc** [comment]
Hi Elizabeth,

Can you take a look at ScopeTest.  It has the warning: 
```
Warning in .ddg.where(name, parent.env(env)) : Can't find x
```
This is from line 34 of the R script.  While it puts out that warning, it is creating a data node that gets linked in correctly.

**Comment by fong22e** [comment]
Hi Barbara,

Yes, it unfortunately does that. This comes from `.ddg.where`, where it throws the warning when an existing scope could not be found for a particular variable. In assignment cases, the methods calling it will set the environment to `globalenv()` and the ddg will be linked correctly. 

However, `.ddg.where` is also used in `.ddg.get.env`. It is not a problem if an environment could not be found for a particular variable in assignment cases, where the user is most likely aware of it, but it may not be so for non-assignment cases. In those cases, it may be necessary to warn the users that the variable could not be found.

Thank you very much,
Elizabeth

**Comment by blernermhc** [comment]
That's great!  It passes the regression tests now.  

RDataTracker.R has changed since you started this branch, so it needs to get merged.  There are quite a few changes, but I don't think there are any actual conflicts.  How do you feel about doing the merge?  You can click on the "command line instructions" link above to see the git steps to take.  If you feel uncertain, we could do this together after the Skype call on Tuesday.

**Comment by fong22e** [comment]
Hi Barbara,

I can try! But it says here that I am not authorized to merge this pull request.

Thank you very much,
Elizabeth

**Comment by blernermhc** [comment]
Right.  You can merge development into your branch.  Then do a commit & push.  That will update the pull request, but at that point it should not have any conflicts.  Then one of us will merge the pull request.

**Comment by fong22e** [comment]
Ok! I will try!

**Comment by fong22e** [comment]
Hi Barbara, the merge is complete!

**Comment by blernermhc** [comment]
This looks good.  It looks like you've fixed a problem with CalculateSquareRoot with this fix, so you should also update its expected result.  To do that say:

ant -file tests.xml update-CalculateSquareRoot

and

ant -file tests-ddg-txt.xml update-CalculateSqureRoot

Then you can commit and push again.

**Comment by fong22e** [comment]
It is done, Barbara! How does that look?

**Pull request merged**
