### PR TITLE
Control2

### PR DESCRIPTION
**Pull request by erboose**
This update collects provenance for statements inside control constructs (if, for, while, repeat, and simple block) if the parameter annotate.inside in ddg.run is set to TRUE.  The number of times provenance is collected for a given loop (in for, while, and repeat statements) is set by the parameter max.loops.  The user can also set these parameters to a series of default values from the command line using ddg.set.detail.

Provenance is collected for statements inside control constructs (as it is for statements inside functions) by creating and executing an annotated version of the original script.
 
Each internal statement is wrapped with ddg.eval.  A second parameter is added to ddg.eval to point to the corresponding DDGStatement object stored in the ddg environment.

ddg.start and ddg.finish statements are inserted at the top and bottom of each block.

In for statements, a ddg.forloop statement is inserted after ddg.start to create procedure and data nodes for the index variable.

In for, while, and repeat statements, an if-else statement is created to test whether the current loop count is less than or equal to max.loops.  If it is, an annotated version of the block is executed.  If not, an unannotated version of the block is executed.  The function ddg.loop.count(n) retrieves the current loop count for loop n (stored in the ddg environment).

### CODE REVIEW

**Comment by MKLau** [comment]
@erboose 

Hey Emery, this has a lot of merge conflicts with development. It looks like you didn't merge development into your control2 branch first. If you haven't, take a second and do that. 

Let me know if I can help with dealing with the conflicts!

**Comment by erboose** [comment]
Hi Matt,

Since there are a lot of changes, I thought it might be easier for Barb to review them before merging.

Emery

Sent from my iPhone

On Nov 11, 2016, at 10:34 AM, MKLau <notifications@github.com<mailto:notifications@github.com>> wrote:


@erboose<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erboose&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=kbSzXk5uuINmNoo4MekzCE-8oe-IGwHYbug8SQuMN3U&m=rKrt94dwirQFc-zi55Jl6eud74CV2GhtQ64F5hr_ews&s=oG2EkYG--xQYJ1UzhSVXFh9osP7JSmr-rZpF87bW8j8&e=>

Hey Emery, this has a lot of merge conflicts with development. It looks like you didn't merge development into your control2 branch first. If you haven't, take a second and do that.

Let me know if I can help with dealing with the conflicts!

-

**Comment by MKLau** [comment]
Great, thanks Emery.

Matt

On Nov 11, 2016, at 2:25 PM, erboose <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Matt,

Since there are a lot of changes, I thought it might be easier for Barb to review them before merging.

Emery

Sent from my iPhone

On Nov 11, 2016, at 10:34 AM, MKLau <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


@erboose<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erboose&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=kbSzXk5uuINmNoo4MekzCE-8oe-IGwHYbug8SQuMN3U&m=rKrt94dwirQFc-zi55Jl6eud74CV2GhtQ64F5hr_ews&s=oG2EkYG--xQYJ1UzhSVXFh9osP7JSmr-rZpF87bW8j8&e=>

Hey Emery, this has a lot of merge conflicts with development. It looks like you didn't merge development into your control2 branch first. If you haven't, take a second and do that.

Let me know if I can help with dealing with the conflicts!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_End-2Dto-2Dend-2Dprovenance_RDataTracker_pull_181-23issuecomment-2D259983164&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=kbSzXk5uuINmNoo4MekzCE-8oe-IGwHYbug8SQuMN3U&m=rKrt94dwirQFc-zi55Jl6eud74CV2GhtQ64F5hr_ews&s=shMa4OJS1J8QgzU70XfawoZtzwrNMxHwZMJI22oF2dM&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHHAKzye13fuBBNORZQqL8hSn8ksSXUtks5q9IsRgaJpZM4Ku7q2&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=kbSzXk5uuINmNoo4MekzCE-8oe-IGwHYbug8SQuMN3U&m=rKrt94dwirQFc-zi55Jl6eud74CV2GhtQ64F5hr_ews&s=hzjud7mFlfylukjOjscxXNKLnsJaUbV2pyxw2VzrWV4&e=>.

-

**Comment by blernermhc** [comment]
I've reviewed the codes and done a small amount of refactoring.  I have committed and pushed those changes so they are now part of the pull request.  The test cases for if-statements look good, but I'm not sure about the ddgs we are getting for loops.  They seem to only show what happens on the first iteration of the loop.  For example:
- For the repeat test on lines 23-28, I think we should see multiple assignments to d.  Its value is 4 entering the loop, and should be 7 on exit, but I just see one assignment, so the ddg shows 5 as its value on exit.

**Comment by blernermhc** [comment]
Also, when I look on github, I see an expected folder that contains a ddg.txt file.  That version seems to have all the iterations of the loops.  However, the file in expected_ControlConstructTest_ddg.txt does not.

**Comment by erboose** [comment]
In ddg.run the parameter max.loops is currently set to 1 by default to avoid excessive run times.  To collect provenance for all iterations, set max.loops = -1 (or an arbitrary large number) or use ddg.set.detail(3) at the R command line.

If the actual number of iterations exceeds the value of max.loops, the final value of a variable modified in the loop will not be displayed.  I was hoping to get some feedback here on what we would like to see.  One possibility would be to add a data node containing the final value connected by an edge to the finish node for the control statement.  Any thoughts?

**Comment by blernermhc** [comment]
Thanks for that explanation.  I now understand why the ddg looks as it does and why there are 2 different expected results.

I think the current ddg when not all iterations of the loop are recorded is misleading since, as you note, the data node might not contain the final value of the variables written, yet, will get hooked up to later uses of the variable.  

I think it would be good for the ddg to somehow explicitly record the fact that it is incomplete because with the current output, the scientist viewing the ddg, or any software using the collected provenance would have no way of distinguishing between the case where there was only 1 iteration, or there were many iterations but only 1 recorded.  I'm not sure what the best way to do that would be but it seems like we need some kind of "details omitted" node which has output data nodes whose values correspond to the final values of the data when the loop exits.

This is similar to what we do in Console mode where we only put a data node at the last assignment to a variable since we do not have access to intermediate values in Console mode.

**Comment by erboose** [comment]
Agreed.  Using the existing code it should be possible to test for cases where the ddg is incomplete because the number of actual iterations exceeds the current value of max.loops.  What would be the best way to record and display such cases?  I like the idea of a "details omitted" node.  Is there any precedence for this in the Prov world?

**Comment by erboose** [comment]
So here's a straw man solution:  Suppose m= the current value of max.loops, n = the actual number of iterations of a particular loop, and x = a variable whose value is modified in the loop, where m < n.  Capture provenance for the first m iterations of the loop plus the final nth iteration (taking into account next and break statements).  The final value of x would then be captured in the ddg.  Add a "completeness" attribute to the DDGStatement class.  If the completeness attribute for a given control statement is false, indicate this in the visual representation (e.g. add "Incomplete" to the labels for start and end nodes for the control statement).  Thoughts?

**Comment by erboose** [comment]
On second thought it may be difficult to identify the final iteration of a loop until it is actually executed, at which point it is too late to collect provenance, except in the case of a for loop without break or next statements.  But I think Barb's suggestion would work.

**Comment by erboose** [comment]
The last two updates address this problem by creating a "Details Omitted" node after the last annotated loop iteration and adding output data nodes containing final values to the finish node for the control statement.  The Details Omitted node is currently implemented as a procedure node of type "Operation", though typically it serves as a place holder for both missing procedure and data nodes.

Barb and I are wondering about creating a new type of procedure node called "Incomplete" that could be used for this purpose and displaying it in a different color in DDG Explorer.  Though it is currently possible to find such nodes in DDG Explorer by searching for "Details Omitted", a different color might help to make such nodes stand out for users.

Adding a new type of procedure node will have implications for the JSON file and perhaps for other parts of our project.  What do folks think?

**Comment by MKLau** [comment]
Hi Emery, I don't have an objection to that, but, recognizing that I don't fully understand the mechanics of the provenance capture, I'm wondering if it's possible to always record the last executed iteration of a loop and delete it from memory if the next line of executed code is not loop ending. Would that work to solve the issue of recording the last line of a loop?

Also, I think we should prioritize a solution that avoids causing JSON implementation issues. If the "Incomplete" node is going to seriously inhibit getting the project on board with using the prov standard output, we should consider another way around it.

Matt

On Dec 2, 2016, at 2:17 PM, erboose <notifications@github.com<mailto:notifications@github.com>> wrote:


The last two updates address this problem by creating a "Details Omitted" node after the last annotated loop iteration and adding output data nodes containing final values to the finish node for the control statement. The Details Omitted node is currently implemented as a procedure node of type "Operation", though typically it serves as a place holder for both missing procedure and data nodes.

Barb and I are wondering about creating a new type of procedure node called "Incomplete" that could be used for this purpose and displaying it in a different color in DDG Explorer. Though it is currently possible to find such nodes in DDG Explorer by searching for "Details Omitted", a different color might help to make such nodes stand out for users.

Adding a new type of procedure node will have implications for the JSON file and perhaps for other parts of our project. What do folks think?

-

**Comment by erboose** [comment]
Hi Matt,

So far I haven’t thought of a way to identify the last iteration of a loop without actually executing it.  So, yes, it would be possible to store provenance for each iteration and then discard it if another iteration follows.  However, if the control statement occurs at a high level in a complex script, that could amount to a major hit in performance.

I don’t foresee any problems with the JSON file—it’s just a different possible value of the type attribute for an activity—but we thought we should ask.

Thanks,
Emery

**Comment by erboose** [comment]
A new parameter (first.loop) was added to ddg.run to set the first iteration of a loop to annotate in for, repeat, and while statements.  If first.loop > 1 (the default value), a Details Omitted node is inserted before the first annotated iteration.  The number of annotated iterations is set by the parameter max.loops in ddg.run or by the function ddg.set.detail at the R command line.

**Comment by erboose** [comment]
If annotate.inside=TRUE, provenance is collected for statements inside functions and inside control constructs (unless, in the latter case, max.loops=0).  This is accomplished by creating and executing an annotated version of the original script.  The annotations added to functions were modified by adding a conditional statement so that provenance is not collected for a function if it is called from inside a control loop where provenance is not collected (in other words, where the iteration is represented by a Details Omitted node).

**Pull request merged**
