### PR TITLE
Fixed bugs that caused the regression tests to fail

### PR DESCRIPTION
**Pull request by fong22e**
Regression tests failed to pass with the last update to ValType. They should pass now.

### CODE REVIEW

**Comment by MKLau** [comment]
Great, thanks Elizabeth!

**Comment by erboose** [comment]
Some remaining issues on development:

Installing with ant (ant install) generates a warning that the function signature for ddg.init in the documentation (InitSave.Rd) does not match the function signature in the code (RDataTracker.R).  The former should be updated to match the latter.

Running the regression tests (ant -file tests.xml) identifies three tests where actual results do not match expected results: basicTest, RMarkdownTest, and HFDatasetPreview.

**Comment by MKLau** [comment]
OK, I'll turn these into issues.

**Comment by MKLau** [comment]
See #286 and #287

**Pull request merged**
