### PR TITLE
ScriptNum for Start and Finish nodes = 1

### PR DESCRIPTION
**Pull request by fong22e**
`DailySolarRadiation` still fails on Windows for `rdt`. Barbara, could you please update that?

### CODE REVIEW

**Comment by fong22e** [comment]
I'm sorry!

**Comment by blernermhc** [comment]
We have some progress!  jsonvalidate can now build!!!

The tests are failing, though, because the JSON is different.  I believe this is caused by Travis using R 4.  For example one of the differences is because the valType for a node now has a string instead of a factor, which is definitely an R 4 change.

**Comment by fong22e** [comment]
Which test is it in? I remember there are some cases where the factor is there deliberately.

**Comment by blernermhc** [comment]
It failed the basic test

**Pull request merged**
