### PR TITLE
Incremental drawing

### PR DESCRIPTION
**Pull request by moepwintphyu1996**
I have fixed the bug for incremental drawing! Please take a look at my code.

### CODE REVIEW

**Comment by MKLau** [comment]
Hi Moe, thanks for working on this. 

I just ran this with an analytical script that first with incremental=FALSE and then with incremental=TRUE. It runs fine without using the incremental feature. When I use incremental, I get the following:

 > ddg.run('analyses.R','../data/ddg',incremental=TRUE)                                                                                                       
 Error: Unable to access jarfile NA/RDataTracker/java/DDGExplorer.jar                                                                                         
 Error in socketConnection(host = "localhost", port = 6096, blocking = FALSE,  :                                                                              
   cannot open the connection                                                                                                                                 
 In addition: Warning messages:                                                                                                                               
 1: In min(which(check.library.paths == TRUE)) :                                                                                                              
   no non-missing arguments to min; returning Inf                                                                                                             
 2: In socketConnection(host = "localhost", port = 6096, blocking = FALSE,  :                                                                                 
   localhost:6096 cannot be opened                                                                                                                            
 Error: evaluation nested too deeply: infinite recursion / options(expressions=)?                                                                             
 In addition: There were 50 or more warnings (use warnings() to see the first 50) 

Here's the last warning:

50: In .ddg.insert.error.message(error.msg) :                                                                                                                
   No binding for con . DDG may be incorrect! 

Do you have an example that's working for you that I could try running?

**Comment by blernermhc** [comment]
Matt, Can you run it with display = TRUE:

ddg.run('analyses.R','../data/ddg',disp=TRUE)

**Comment by MKLau** [comment]
Hi Barbara, just tried it with the incerementalDrawing branch with both disp=TRUE,incremental=FALSE and dis=TRUE,incremental=TRUE, and I'm still getting the same error:

Error: Unable to access jarfile NA/RDataTracker/java/DDGExplorer.jar                                                                                                             
 Error in socketConnection(host = "localhost", port = 6096, blocking = FALSE,  :                                                                                                  
   cannot open the connection                                                                                                                                                     
 In addition: Warning messages:                                                                                                                                                   
 1: In min(which(check.library.paths == TRUE)) :                                                                                                                                  
   no non-missing arguments to min; returning Inf                                                                                                                                 
 2: In socketConnection(host = "localhost", port = 6096, blocking = FALSE,  :                                                                                                     
   localhost:6096 cannot be opened                                                                                                                                                
 Error: evaluation nested too deeply: infinite recursion / options(expressions=)?                                                                                                 
 In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by tfjmp** [comment]
Before merging, should we discuss the way we want to implement support for the front end? We are adding a bunch of code specific to DDGExplorer. Is it still the direction we want to go?

**Comment by blernermhc** [comment]
Matt, Given the error you were reporting, I think the problem is with the display parameter, rather than with the incremental parameter.

**Comment by blernermhc** [comment]
Thomas, yes, we can hold off merging until we discuss this.

**Comment by moepwintphyu1996** [comment]
Matt, it might be because you don't have the incremental drawing version on DDGExplorer. I thought I did the pull request for the DDG Explorer side but I will do it again.

**Comment by MKLau** [comment]
Hi Moe, thanks, I thought that something like that might be an issue, I updated DDG-Exp. just before trying it, so I updated with the most recent development branch of DDG-Exp. Let me know if you'd like me to try it again with another branch.

**Comment by tfjmp** [comment]
This pull request has been open for a very long time with no progress. Closing it now.

**Pull request closed without merging**
