### PR TITLE
Update snapshot nodes for various data types

### PR DESCRIPTION
**Pull request by erboose**
Create snapshot nodes for long strings and arrays.
Create snapshot nodes for lists in a consistent format.
Save partial snapshots of arrays and lists as needed.

See DataTypeTest.R in regression suite for examples of various data types.

### CODE REVIEW

**Comment by blernermhc** [comment]
Hi Emery,

  In .ddg.is.csv, do we need the check for graphics or simple values?

  What is the reason to handle vectors and lists differently from each other?

Barb

**Comment by erboose** [comment]
Hi Barb,

Currently .ddg.is.csv is only called by .ddg.save.data, which checks for graphics and simple values before calling .ddg.is.csv.  I opted to leave the checks for graphics and simple values in .ddg.is.csv to be on the safe side, in case other parts of the code are changed.  But they could be removed as you think best.

.ddg.is.csv is designed to return TRUE for vectors, matrices, and data frames since these data types can be stored successfully and unambiguously as csv files. !is.list is included in the check for vectors because is.vector returns TRUE for vector and lists while is.list returns TRUE for lists and data frames.

Emery

**Comment by blernermhc** [comment]
It seems to me that the test for graphic is unnecessary in .ddg.is.csv as it will fail the other tests if it is a graphic.  Probably keeping the is.simple.value makes sense since what we think of as simple values are really vectors of length 1 in R's view.

You can go ahead and merge this into development.

**Comment by erboose** [comment]
Lots of git problems so I made these changes directly to development and added the ddg.display.ddg function.

**Pull request closed without merging**
